---
apiVersion: v1
kind: Service
metadata:
  name: world
  namespace: world
spec:
  type: ClusterIP
  selector:
    service: world
  ports:
  - port: 80
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: world
  namespace: world
spec:
  replicas: 1
  selector:
    matchLabels:
      service: world
  template:
    metadata:
      labels:
        service: world
    spec:
      containers:
      - name: world
        image: the-world:0.0.1
        # imagePullPolicy: Always
        env:
        - name: CONNECTION_STRING
          value: "postgres://world_service:EcSljwBeVIG42KLO0LS3jtuh9x6RMcOBZEWFSk@cockroachdb-public.cockroachdb:26257/the_world?sslmode=allow"
        ports:
        - name: http
          containerPort: 8888
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
