---
apiVersion: v1
kind: Service
metadata:
  name: world-gui
  namespace: world
spec:
  type: ClusterIP
  selector:
    service: world-gui
  ports:
  - port: 80
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: world-gui
  namespace: world
spec:
  replicas: 1
  selector:
    matchLabels:
      service: world-gui
  template:
    metadata:
      labels:
        service: world-gui
    spec:
      containers:
      - name: world-gui
        image: %TAG%
        ports:
        - name: http
          containerPort: 8888
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
