---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: gui-mapping
  namespace: world
spec:
  hostname: "*"
  prefix: /world/
  service: world-gui.world
  rewrite: /
  timeout_ms: 0
